### ISSUE TITLE
Change user sign-in response from plain JSON to header content

### ISSUE THREAD

**Issue by sakozz** [sunil-shrestha/multimodel_devise#1]
At the moment the sign-in response sends the user auth-token and other data in plain JSON. It is probably better to response via headers. Then in the front-end, we can use [Angular2-token](https://github.com/neroniaky/angular2-token) or impliment in the similar way. Example below from https://github.com/neroniaky/angular2-token/blob/a16dcee34c763a1142a87f34dc282d6f88d1bb7d/src/angular2-token.service.ts#L441

```

 let authData: AuthData = {
            accessToken:    headers.get('access-token'),
            client:         headers.get('client'),
            expiry:         headers.get('expiry'),
            tokenType:      headers.get('token-type'),
            uid:            headers.get('uid')
};

```

**Comment by sunil-shrestha** [comment]
Included in the commit https://github.com/sunil-shrestha/multimodel_devise/commit/d0cd08aeb6770866fd2cd805f8fa4ef4f88f0916

**Comment by sakozz** [comment]
Included in the commit https://github.com/sunil-shrestha/multimodel_devise/commit/d0cd08aeb6770866fd2cd805f8fa4ef4f88f0916
